workflows:
  version: 2
  workflow:
    jobs:
      - build
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - run:
          name: Integration Testing
          command: |
            . venv/bin/activate
            python3 -m unittest tests/test_*.py
